In [1]:
#NUMPY AND PANDAS- packages helps in processing of data
#NUMPY:- mathematical and stats operations. works on array and matrix

In [2]:
import numpy as np

In [4]:
# basic array creation methods:
# 1 all elements are 1

In [5]:
# np.ones(no. of elements)
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
g=np.ones(8)

In [8]:
g.dtype


dtype('float64')

In [10]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
# 2 all elements 0

In [13]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros(9,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
h=np.zeros(9,dtype = int)
h

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
#identity matrix
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [18]:
s=np.eye(6)

In [19]:
#to get no. of dimensions
s.ndim

2

In [21]:
g.ndim

1

In [22]:
h=np.array([1,6,9,34,7,"kite",34.65])

In [23]:
h

array(['1', '6', '9', '34', '7', 'kite', '34.65'], dtype='<U32')

In [24]:
h.ndim

1

In [29]:
l=np.array([['light','electricity'],['led','battery']])

In [30]:
l

array([['light', 'electricity'],
       ['led', 'battery']], dtype='<U11')

In [31]:
l.ndim

2

In [32]:
l.dtype


dtype('<U11')

In [38]:
#acess a single value
l[0][0]

'light'

In [40]:
#$ row,cloumn
l[1][0]

'led'

In [42]:
l[1,1]

'battery'

In [43]:
s

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [44]:
# size of matrix gives total number of elements
# shape tells number of rows and columns


In [45]:
s.size

36

In [46]:
s.shape

(6, 6)

In [47]:
# arange:- create an array for the decided range

In [202]:
ar=np.arange(1,21,2)
#(start, end,step)

In [49]:
ar

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [50]:
ar.size

10

In [51]:
ar.reshape(5,2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [52]:
ar.reshape(5,2).ndim

2

In [73]:
#for 3d array
f = np.arange(1,24,2)

In [74]:
f

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [81]:
#1d array to multidimension array
f=f.reshape(3,2,2)

In [82]:
f

array([[[ 1,  3],
        [ 5,  7]],

       [[ 9, 11],
        [13, 15]],

       [[17, 19],
        [21, 23]]])

In [86]:
# to give in reshape we give from high dimension to low dimension
# col:- 1d
# row:- 2d
# height:= 3d

In [87]:
# single array----> 1,11,9,19,23

In [88]:
f[[2,1],[1],[1]]

array([23, 15])

In [99]:
f[[0,1,1,2,2],[0,0,0,0,1],[0,1,0,1,1]]

array([ 1, 11,  9, 19, 23])

In [100]:
#random 

In [119]:
r=np.random.randint(1,20,8)

In [126]:
r=r.reshape(4,2)
r

array([[18,  6],
       [15,  6],
       [ 4,  2],
       [ 9, 12]])

In [127]:
# using iterators print index vlaues for number
n=int(input("enter a number:- "))
for i in range (len(r)):
    for j in range (len(r[i])):
        if n==r[i,j]:
            row=i
            col=j
            print('col:-',j)
            print('row:-',i)

enter a number:- 18
col:- 0
row:- 0


In [157]:
tr=np.random.randint(1,20,12)

In [158]:
tr=tr.reshape(2,2,3)
tr

array([[[19,  1, 11],
        [ 5,  6,  8]],

       [[ 8, 15, 10],
        [19, 14,  6]]])

In [159]:
n=int(input("enter a number:- "))
for k in range (len(tr)):
    for i in range (len(tr[k])):
        for j in range (len(tr[i])):
            if n==tr[k,i,j]:
                row=i
                col=j
                print('col:-',j)
                print('row:-',i)
                print('height:-',k)

enter a number:- 19
col:- 0
row:- 0
height:- 0
col:- 0
row:- 1
height:- 1


In [160]:
# for sum function
#np.sum(tr,axis=1,2,3)
# to give axis we follow
# col:- 1
# row:- 2
# height:= 3


In [171]:
np.sum(tr,axis=2)

array([[31, 19],
       [33, 39]])

In [165]:
np.sum(tr)

122

In [166]:
np.max(tr,axis=0)

array([[19, 15, 11],
       [19, 14,  8]])

In [170]:
#wap to print avg using loop

In [173]:
s=0
c=0
for k in range (len(tr)):
    for i in range (len(tr[k])):
        for j in range (len(tr[i])):
            c=c+1
            s=s+tr[k][j][i]
print('avg = ',s/c)
                

avg =  10.875


In [183]:
j=np.sum(tr,axis=0)
j

array([[27, 16, 21],
       [24, 20, 14]])

In [184]:
p=1
for i in j:
    p*=i
p
    

array([648, 320, 294])

In [185]:
r

array([[18,  6],
       [15,  6],
       [ 4,  2],
       [ 9, 12]])

In [187]:
r.T
# FOR TRANSPOSE WE USE"T"

array([[18, 15,  4,  9],
       [ 6,  6,  2, 12]])

In [189]:
r.flatten()
#flatten reduces from 2d to 1d

array([18,  6, 15,  6,  4,  2,  9, 12])

In [190]:
#product:= 
# dot prod--> scaler
# cross--> vector

In [192]:
m1 = np.arange(1,13).reshape(6,2)
m1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [193]:
m2 = np.arange(1,25,2).reshape(6,2)
m2

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19],
       [21, 23]])

In [194]:
#dot product:
m1*m2

array([[  1,   6],
       [ 15,  28],
       [ 45,  66],
       [ 91, 120],
       [153, 190],
       [231, 276]])

In [197]:
r=int(int(input()))
c=int(int(input()))
np.eye(r,c)

5
6


array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [203]:
ar=np.arange(1,21,2)

In [204]:
ar

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [205]:
ar.reshape(5,2)


array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [206]:
ar.flatten()

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [207]:
np.max(ar)

19

In [208]:
np.min(ar)

1

In [210]:
f

array([[[ 1,  3],
        [ 5,  7]],

       [[ 9, 11],
        [13, 15]],

       [[17, 19],
        [21, 23]]])

In [211]:
np.min(f,axis=2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21]])

In [212]:
np.max(f,axis=2)

array([[ 3,  7],
       [11, 15],
       [19, 23]])

In [213]:
np.mean(f,axis=2)

array([[ 2.,  6.],
       [10., 14.],
       [18., 22.]])

In [1]:
##############################################################################################
##############################################################################################
##############################################################################################
# PANDAS:-- TABULAR DATA WITH NAMINGS AND LABELS


In [3]:
import pandas as pd

In [3]:
#series:- labelled 1d array

In [31]:
a=np.random.randint(1,10,5)

In [32]:
a.size

5

In [33]:
a.ndim

1

In [34]:
pd.Series(a)
#Series ---> s caps

0    5
1    7
2    1
3    6
4    2
dtype: int32

In [35]:
physics=pd.Series(a,index=['aa','bb','cc','dd','ef'])

In [36]:
m=np.random.randint(1,10,5)
m

array([8, 9, 5, 2, 6])

In [37]:
maths=pd.Series(a,index=['aa','bb','cc','dd','ef'])

In [38]:
physics

aa    5
bb    7
cc    1
dd    6
ef    2
dtype: int32

In [39]:
maths

aa    5
bb    7
cc    1
dd    6
ef    2
dtype: int32

In [40]:
#to combine 2 series together in a table
pd.concat((physics,maths))

aa    5
bb    7
cc    1
dd    6
ef    2
aa    5
bb    7
cc    1
dd    6
ef    2
dtype: int32

In [41]:
pd.concat((physics,maths),axis=1)

0  1
aa  5  5
bb  7  7
cc  1  1
dd  6  6
ef  2  2

In [42]:
marks=pd.concat((physics,maths),axis=1)
marks.columns=['phy','maths']
marks

phy  maths
aa    5      5
bb    7      7
cc    1      1
dd    6      6
ef    2      2

In [43]:
type(maths)

pandas.core.series.Series

In [44]:
type(marks)

pandas.core.frame.DataFrame

In [45]:
#data frame:- when we provide labels to 2d entity

In [47]:
# add new row in marks table for student "GH" AND "KI"

In [1]:
ad = pd.DataFrame(l,index = n, columns=['phy','maths'])

NameError: name 'pd' is not defined

In [57]:
marks=pd.concat((marks,ad))

In [58]:
marks

phy maths
aa   5     5
bb   7     7
cc   1     1
dd   6     6
ef   2     2
gh   8     7
ki   9     1

In [59]:
#indexing based on index numbers: iloc    indexing 0 se start krna h

In [60]:
#marks.iloc[row,col]
marks.iloc[2,1]

1

In [64]:
marks.iloc[0,0]

5

In [65]:
marks.iloc[5,1]

'7'

In [66]:
marks.iloc[3,0]

6

In [67]:
marks.iloc[2,1]

1

In [68]:
marks.iloc[1,1]

7

In [71]:
###### indexing based on labels:   loc
# marks.loc['row ka naam','col ka naam']

In [72]:
marks.loc['aa','phy']

5

In [76]:
marks.values
#matrix ki vlaues ko array mein convert krke array operations use kr skte h

array([[5, 5],
       [7, 7],
       [1, 1],
       [6, 6],
       [2, 2],
       ['8', '7'],
       ['9', '1']], dtype=object)

In [82]:
marks.loc[['aa','bb'],['phy','maths']]

phy maths
aa   5     5
bb   7     7